name: Build Misskey Docker Image

on:
  workflow_dispatch:
  repository_dispatch:
    types: [run]

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout Misskey Repository
        uses: actions/checkout@v3
        with:
          repository: 'misskey-dev/misskey'
          ref: 'master'
          submodules: 'recursive'
      -
        name: Replace Assets URL
        run: find ./packages -type f \( -name "*.vue" -o -name "*.pug" \) -exec sed -i 's/https:\/\/xn--931a\.moe\/assets/https:\/\/oss\.isle\.moe\/assets/g' {} \;
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      -
        name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push
        uses: docker/build-push-action@v3
        with:
          context: .
          platforms: linux/amd64
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/${{ secrets.DOCKERHUB_REPO }}:${{ secrets.DOCKERHUB_TAG }}
